import { Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'lib-input',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './input.component.html',
  styleUrl: './input.component.css',
})
export class InputComponent {
  // Optional input for the label
  @Input() label: string = '';

  // Type of the input field
  @Input() type: string = 'text'; // it is text by default

  // Input field placeholder (optional)
  @Input() placeholder: string = '';

  // Current value of the input field
  @Input() value: string = '';

  // Name for the input field
  @Input() name: string = '';

  // Id for input field and connection with label, autogenerated if not given
  @Input() id: string =
    'lib-input-' + Math.random().toString(36).substring(2, 9);

  // Tells the father every time the user writes something
  @Output() valueChange = new EventEmitter<string>();

  // This event gets the native keyboard event
  onInputChange(event: Event) {
    const inputElement = event.target as HTMLInputElement;
    this.valueChange.emit(inputElement.value);
  }
}
