import { Component, EventEmitter, Input, Output, forwardRef } from '@angular/core';
import { CommonModule } from '@angular/common';
import { ControlValueAccessor, NG_VALUE_ACCESSOR } from '@angular/forms';

@Component({
  selector: 'lib-input',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './input.component.html',
  styleUrl: './input.component.css',
  providers: [
    {
      provide: NG_VALUE_ACCESSOR,
      useExisting: forwardRef(() => InputComponent),
      multi: true
    }
  ]
})
export class InputComponent implements ControlValueAccessor {
  // Optional input for the label
  @Input() label: string = '';

  // Type of the input field
  @Input() type: string = 'text'; // it is text by default

  // Input field placeholder (optional)
  @Input() placeholder: string = '';

  // Current value of the input field
  @Input() value: string = '';

  // Name for the input field
  @Input() name: string = '';

  // Id for input field and connection with label, autogenerated if not given
  @Input() id: string =
    'lib-input-' + Math.random().toString(36).substring(2, 9);

  // Tells the father every time the user writes something
  @Output() valueChange = new EventEmitter<string>();

  onChange: any = () => {};
  onTouched: any = () => {};

  writeValue(value: any): void {
    this.value = value || '';
  }

  registerOnChange(fn: any): void {
    this.onChange = fn;
  }

  registerOnTouched(fn: any): void {
    this.onTouched = fn;
  }

  setDisabledState?(isDisabled: boolean): void {
  }

  // This event gets the native keyboard event
  onInputChange(event: Event) {
    const inputElement = event.target as HTMLInputElement;
    this.value = inputElement.value;
    this.valueChange.emit(this.value);
    this.onChange(this.value);
    this.onTouched();
  }
}
