import { Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'lib-switch',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './switch.component.html',
  styleUrl: './switch.component.css',
})
export class SwitchComponent {
  // Optional input for the label
  @Input() label: string = '';

  // Current checked state of the switch
  @Input() checked: boolean = false;

  // Name for the input field
  @Input() name: string = '';

  // Id for input field and connection with label, autogenerated if not given
  @Input() id: string =
    'lib-switch-' + Math.random().toString(36).substring(2, 9);

  // Tells the father every time the switch is toggled
  @Output() checkedChange = new EventEmitter<boolean>();

  // This event gets the native click/change event
  onToggle(event: Event) {
    const inputElement = event.target as HTMLInputElement;
    this.checkedChange.emit(inputElement.checked);
  }
}
